<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace GPBMetadata;

class Api
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa7010a096170692e70726f746f120361706922180a08506f7374536c75" .
            "67120c0a046e616d6518012001280922370a0a506f73744f626a65637412" .
            "0a0a026964180120012803120c0a046e616d65180220012809120f0a0763" .
            "6f6e74656e7418032001280932330a04506f7374122b0a07476574506f73" .
            "74120d2e6170692e506f7374536c75671a0f2e6170692e506f73744f626a" .
            "656374220042055a03617069620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

