// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// PostSlug is the name of the post that is desired e.g. "post-you-may-like-2018-9".
type PostSlug struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostSlug) Reset()         { *m = PostSlug{} }
func (m *PostSlug) String() string { return proto.CompactTextString(m) }
func (*PostSlug) ProtoMessage()    {}
func (*PostSlug) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *PostSlug) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostSlug.Unmarshal(m, b)
}
func (m *PostSlug) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostSlug.Marshal(b, m, deterministic)
}
func (m *PostSlug) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostSlug.Merge(m, src)
}
func (m *PostSlug) XXX_Size() int {
	return xxx_messageInfo_PostSlug.Size(m)
}
func (m *PostSlug) XXX_DiscardUnknown() {
	xxx_messageInfo_PostSlug.DiscardUnknown(m)
}

var xxx_messageInfo_PostSlug proto.InternalMessageInfo

func (m *PostSlug) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Post is the Post object that contains info about the post.
type PostObject struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostObject) Reset()         { *m = PostObject{} }
func (m *PostObject) String() string { return proto.CompactTextString(m) }
func (*PostObject) ProtoMessage()    {}
func (*PostObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *PostObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostObject.Unmarshal(m, b)
}
func (m *PostObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostObject.Marshal(b, m, deterministic)
}
func (m *PostObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostObject.Merge(m, src)
}
func (m *PostObject) XXX_Size() int {
	return xxx_messageInfo_PostObject.Size(m)
}
func (m *PostObject) XXX_DiscardUnknown() {
	xxx_messageInfo_PostObject.DiscardUnknown(m)
}

var xxx_messageInfo_PostObject proto.InternalMessageInfo

func (m *PostObject) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PostObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PostObject) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*PostSlug)(nil), "api.PostSlug")
	proto.RegisterType((*PostObject)(nil), "api.PostObject")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostClient is the client API for Post service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostClient interface {
	// GetPost takes in certain query params and returns a Post.
	GetPost(ctx context.Context, in *PostSlug, opts ...grpc.CallOption) (*PostObject, error)
}

type postClient struct {
	cc *grpc.ClientConn
}

func NewPostClient(cc *grpc.ClientConn) PostClient {
	return &postClient{cc}
}

func (c *postClient) GetPost(ctx context.Context, in *PostSlug, opts ...grpc.CallOption) (*PostObject, error) {
	out := new(PostObject)
	err := c.cc.Invoke(ctx, "/api.Post/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServer is the server API for Post service.
type PostServer interface {
	// GetPost takes in certain query params and returns a Post.
	GetPost(context.Context, *PostSlug) (*PostObject, error)
}

func RegisterPostServer(s *grpc.Server, srv PostServer) {
	s.RegisterService(&_Post_serviceDesc, srv)
}

func _Post_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostSlug)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Post/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).GetPost(ctx, req.(*PostSlug))
	}
	return interceptor(ctx, in, info, handler)
}

var _Post_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Post",
	HandlerType: (*PostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPost",
			Handler:    _Post_GetPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x92, 0xe3, 0xe2, 0x08, 0xc8,
	0x2f, 0x2e, 0x09, 0xce, 0x29, 0x4d, 0x17, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0xbc, 0xb8, 0xb8, 0x40, 0xf2, 0xfe, 0x49, 0x59,
	0xa9, 0xc9, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x60, 0x79, 0xe6, 0x20, 0xa6, 0xcc, 0x14,
	0xb8, 0x0e, 0x26, 0x84, 0x0e, 0x21, 0x09, 0x2e, 0xf6, 0xe4, 0xfc, 0xbc, 0x92, 0xd4, 0xbc, 0x12,
	0x09, 0x66, 0xb0, 0x30, 0x8c, 0x6b, 0x64, 0xcc, 0xc5, 0x02, 0x32, 0x4b, 0x48, 0x9b, 0x8b, 0xdd,
	0x3d, 0xb5, 0x04, 0xcc, 0xe4, 0xd5, 0x03, 0xb9, 0x07, 0xe6, 0x02, 0x29, 0x7e, 0x38, 0x17, 0x62,
	0xa1, 0x12, 0x83, 0x13, 0x6b, 0x14, 0xc8, 0x9d, 0x49, 0x6c, 0x60, 0x37, 0x1b, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xdf, 0x9d, 0x3d, 0x91, 0xc0, 0x00, 0x00, 0x00,
}
